parser: "@typescript-eslint/parser"
parserOptions:
  project: "**/tsconfig.json"
  sourceType: module
plugins:
  - "@typescript-eslint/eslint-plugin"
  - prettier
extends:
  - plugin:@typescript-eslint/recommended
root: true
env:
  node: true
  jest: true
rules:
  "prettier/prettier": error
